# Generated by Django 5.2.7 on 2025-11-05 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('is_correct', models.BooleanField(verbose_name=False)),
                ('like_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('question_text', models.TextField(max_length=1000)),
                ('is_hot', models.BooleanField(verbose_name=True)),
                ('like_count', models.IntegerField()),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionanswer')),
                ('tags', models.ManyToManyField(to='questions.tag')),
            ],
        ),
    ]
