# Generated by Django 5.2.7 on 2025-11-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': 'Лайк на ответе', 'verbose_name_plural': 'Лайки на ответе'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': 'Лайк на вопросе', 'verbose_name_plural': 'Лайки на вопросе'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
