# Generated by Django 5.2.7 on 2025-11-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answerlike_options_alter_questionlike_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlike',
            old_name='like',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='questionlike',
            old_name='like',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_hot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='questions.tag'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('author', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('author', 'question')},
        ),
    ]
